export const APP_NAME = 'VeriQ';
export const APP_TAGLINE = 'Secure Every Question Paper. Verify Every Action.';
export const PROBLEM_STATEMENT = 'WB-03 — Secure Examination Paper Distribution Using Blockchain';

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  PAPER_SETTER = 'PAPER_SETTER',
  CENTRE_ADMIN = 'CENTRE_ADMIN',
  INVIGILATOR = 'INVIGILATOR',
}

export enum PaperStatus {
  DRAFT = 'DRAFT',
  APPROVED = 'APPROVED',
  ASSIGNED = 'ASSIGNED',
  RELEASE_SCHEDULED = 'RELEASE_SCHEDULED',
  RELEASED = 'RELEASED',
  REVOKED = 'REVOKED',
}

export enum SecurityLevel {
  STANDARD = 'STANDARD',
  HIGH = 'HIGH',
  MAXIMUM_TOP_SECRET = 'MAXIMUM_TOP_SECRET',
}

export enum BlockchainEventType {
  PAPER_CREATED = 'PAPER_CREATED',
  PAPER_APPROVED = 'PAPER_APPROVED',
  PAPER_HASHED = 'PAPER_HASHED',
  PAPER_ENCRYPTED = 'PAPER_ENCRYPTED',
  PAPER_ASSIGNED = 'PAPER_ASSIGNED',
  CENTRE_AUTHORIZED = 'CENTRE_AUTHORIZED',
  DEVICE_AUTHORIZED = 'DEVICE_AUTHORIZED',
  ACCESS_ATTEMPT = 'ACCESS_ATTEMPT',
  ACCESS_GRANTED = 'ACCESS_GRANTED',
  ACCESS_DENIED = 'ACCESS_DENIED',
  PAPER_RELEASED = 'PAPER_RELEASED',
  PAPER_VERIFIED = 'PAPER_VERIFIED',
  PAPER_REVOKED = 'PAPER_REVOKED',
  INCIDENT_CREATED = 'INCIDENT_CREATED',
}

export enum IncidentType {
  EARLY_ACCESS = 'EARLY_ACCESS',
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
  DEVICE_MISMATCH = 'DEVICE_MISMATCH',
  HASH_MISMATCH = 'HASH_MISMATCH',
  AUTH_FAILURE = 'AUTH_FAILURE',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
}

export enum IncidentSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum DenialReason {
  RELEASE_WINDOW_NOT_STARTED = 'RELEASE_WINDOW_NOT_STARTED',
  RELEASE_WINDOW_EXPIRED = 'RELEASE_WINDOW_EXPIRED',
  UNAUTHORIZED_CENTRE = 'UNAUTHORIZED_CENTRE',
  DEVICE_MISMATCH = 'DEVICE_MISMATCH',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  PAPER_REVOKED = 'PAPER_REVOKED',
  ROLE_INSUFFICIENT = 'ROLE_INSUFFICIENT',
  TAMPERED_HASH = 'TAMPERED_HASH',
}
