export type UserRole = 'SUPER_ADMIN' | 'PAPER_SETTER' | 'CENTRE_ADMIN' | 'INVIGILATOR';

export const USER_ROLES: Record<UserRole, UserRole> = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  PAPER_SETTER: 'PAPER_SETTER',
  CENTRE_ADMIN: 'CENTRE_ADMIN',
  INVIGILATOR: 'INVIGILATOR',
};
